wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736947117.0
    t:
      1:
      - 53
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.11.0
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
