_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.3
            "8":
                - 3
                - 5
            "12": 0.19.3
            "13": windows-amd64
