name: CI Pipeline

on:
  push:
    branches:
      - 07-project  
  pull_request:
    branches:
      - 07-project  # Trigger on pull requests to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Use the appropriate Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r 07-project/requirements.txt pytest
        python3 -m pip list

    - name: Verify Python and Libraries
      run: |
        source venv/bin/activate
        which python3
        python3 --version
        python3 -m pip list
      

    # Step 4: Run unit and integration tests
    - name: Run tests
      run: |
        source venv/bin/activate
        python3 -m pip list
        python3 -m pytest tests/